GestCTI/Models/CampaignPauseCodes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignPauseCodes
    {
        public int Id { get; set; }
        public int IdCampaign { get; set; }
        public int IdPauseCode { get; set; }
        public int MaxDuration { get; set; }
        public int MaxDailyEvents { get; set; }
        public bool AutoReady { get; set; }
        public bool Active { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual PauseCodes PauseCodes { get; set; }
    }
}

GestCTI/Controllers/CampaignPauseCodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestCTI.Models;
using GestCTI.Controllers.Auth;

namespace GestCTI.Controllers
{
    [CustomAuthorize(Roles = "admin")]
    public class CampaignPauseCodesController : Controller
    {
        private DBCTIEntities db = new DBCTIEntities();

        // GET: CampaignPauseCodes
        public ActionResult Index()
        {
            var campaignPauseCodes = db.CampaignPauseCodes.Include(c => c.Campaign).Include(c => c.PauseCodes);
            return View(campaignPauseCodes.ToList());
        }

        // GET: CampaignPauseCodes/Create
        public ActionResult Create()
        {
            ViewBag.IdCampaign = new SelectList(db.Campaign, "Id", "Code");
            ViewBag.IdPauseCode = new SelectList(db.PauseCodes, "Id", "Name");
            return View();
        }

        // POST: CampaignPauseCodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,IdCampaign,IdPauseCode,MaxDuration,MaxDailyEvents,AutoReady,Active")] CampaignPauseCodes campaignPauseCodes)
        {
            if (ModelState.IsValid)
            {
                if (db.CampaignPauseCodes.FirstOrDefault(p => p.IdCampaign == campaignPauseCodes.IdCampaign && p.IdPauseCode == campaignPauseCodes.IdPauseCode) == null)
                {
                    db.CampaignPauseCodes.Add(campaignPauseCodes);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                //Notificar: El pauseCode campaignPauseCodes.PauseCodes.Name ya existe en la campaña campaignPauseCodes.Campaign.Name
            }

            ViewBag.IdCampaign = new SelectList(db.Campaign, "Id", "Code", campaignPauseCodes.IdCampaign);
            ViewBag.IdPauseCode = new SelectList(db.PauseCodes, "Id", "Name", campaignPauseCodes.IdPauseCode);
            return View(campaignPauseCodes);
        }

        // GET: CampaignPauseCodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CampaignPauseCodes campaignPauseCodes = db.CampaignPauseCodes.Find(id);
            if (campaignPauseCodes == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCampaign = new SelectList(db.Campaign, "Id", "Code", campaignPauseCodes.IdCampaign);
            ViewBag.IdPauseCode = new SelectList(db.PauseCodes, "Id", "Name", campaignPauseCodes.IdPauseCode);
            return View(campaignPauseCodes);
        }

        // POST: CampaignPauseCodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IdCampaign,IdPauseCode,MaxDuration,MaxDailyEvents,AutoReady,Active")] CampaignPauseCodes campaignPauseCodes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campaignPauseCodes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCampaign = new SelectList(db.Campaign, "Id", "Code", campaignPauseCodes.IdCampaign);
            ViewBag.IdPauseCode = new SelectList(db.PauseCodes, "Id", "Name", campaignPauseCodes.IdPauseCode);
            return View(campaignPauseCodes);
        }

        // POST: CampaignPauseCodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CampaignPauseCodes campaignPauseCodes = db.CampaignPauseCodes.Find(id);
            campaignPauseCodes.Active = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: CampaignPauseCodes/Activate/5
        [HttpPost, ActionName("Activate")]
        [ValidateAntiForgeryToken]
        public ActionResult Activate(int id)
        {
            CampaignPauseCodes campaignPauseCodes = db.CampaignPauseCodes.Find(id);
            campaignPauseCodes.Active = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestCTI/Views/CampaignPauseCodes/Create.cshtml
@model GestCTI.Models.CampaignPauseCodes

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(@Resources.Admin.Campaigns, "Index", "Campaigns")</li>
    <li>@Html.ActionLink(Resources.Admin.PauseCodeCampaigns, "Index")</li>
    <li class="active">@Resources.Admin.ActionCreateNew</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.ActionCreateNew @Resources.Admin.PauseCodeCampaign</h2>
</div>

<div class="panel panel-default tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">@Resources.Admin.PauseCodeCampaign</a></li>
    </ul>
    <div class="panel-body tab-content">
        <div class="col-md-6 col-lg-offset-3">
            <div class="tab-pane active" id="tab1">
                @using (Html.BeginForm("Create", "CampaignPauseCodes", FormMethod.Post, new { id = "myform" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="control-label col-md-3" for="IdCampaign" style="font-size:small; font-weight: bold">@Resources.Admin.Campaign</label>
                            <div class="col-md-9">
                                @Html.DropDownList("IdCampaign", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.IdCampaign, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="IdPauseCode" style="font-size:small; font-weight: bold">@Resources.Admin.PauseCode</label>
                            <div class="col-md-9">
                                @Html.DropDownList("IdPauseCode", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.IdPauseCode, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="MaxDuration" style="font-size:small; font-weight: bold">@Resources.Admin.MaxDuration</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.MaxDuration, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                <span class="help-block">@Resources.Admin.TimeSec</span>
                                @Html.ValidationMessageFor(model => model.MaxDuration, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="MaxDailyEvents" style="font-size:small; font-weight: bold">@Resources.Admin.MaxDailyEvents</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.MaxDailyEvents, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                @Html.ValidationMessageFor(model => model.MaxDailyEvents, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="AutoReady" style="font-size:small; font-weight: bold">@Resources.Admin.AutoReady</label>
                            <div class="col-md-9" style="padding-top: 5px">
                                @Html.CheckBoxFor(model => model.Active, new { @class = "icheckbox", @checked = "checked" })
                                @Html.ValidationMessageFor(model => model.AutoReady, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="Active" style="font-size:small; font-weight: bold">@Resources.Admin.Active</label>
                            <div class="col-md-9" style="padding-top: 5px">
                                @Html.CheckBoxFor(model => model.Active, new { @class = "icheckbox", @checked = "checked" })
                                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9 ">
                                <input type="submit" value=@Resources.Admin.Save class="btn btn-success btn-block" style = "font-size:medium" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type='text/javascript' src='~/assets/js/plugins/icheck/icheck.min.js'></script>
    <script type="text/javascript" src="~/assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>

    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-select.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/jquery-validation/jquery.validate.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/maskedinput/jquery.maskedinput.min.js'></script>

    <script type="text/javascript">
        $('#myform').validate({});
    </script>
}

GestCTI/Views/CampaignPauseCodes/Edit.cshtml
@model GestCTI.Models.CampaignPauseCodes

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(@Resources.Admin.Campaigns, "Index", "Campaigns")</li>
    <li>@Html.ActionLink(Resources.Admin.PauseCodeCampaigns, "Index")</li>
    <li class="active">@Resources.Admin.ActionEdit</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.ActionEdit </h2>
</div>

<div class="panel panel-default tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">@Resources.Admin.PauseCodeCampaign</a></li>
    </ul>
    <div class="panel-body tab-content">
        <div class="col-md-6 col-lg-offset-3">
            <div class="tab-pane active" id="tab1">
                @using (Html.BeginForm("Edit", "CampaignPauseCodes", FormMethod.Post, new { id = "myform" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            <label class="control-label col-md-3" for="IdCampaign" style="font-size:small; font-weight: bold">@Resources.Admin.Campaign</label>
                            <div class="col-md-9">
                                @Html.DropDownList("IdCampaign", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.IdCampaign, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="IdPauseCode" style="font-size:small; font-weight: bold">@Resources.Admin.PauseCode</label>
                            <div class="col-md-9">
                                @Html.DropDownList("IdPauseCode", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.IdPauseCode, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="MaxDuration" style="font-size:small; font-weight: bold">@Resources.Admin.MaxDuration</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.MaxDuration, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                <span class="help-block">@Resources.Admin.TimeSec</span>
                                @Html.ValidationMessageFor(model => model.MaxDuration, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="MaxDailyEvents" style="font-size:small; font-weight: bold">@Resources.Admin.MaxDailyEvents</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.MaxDailyEvents, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                @Html.ValidationMessageFor(model => model.MaxDailyEvents, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="AutoReady" style="font-size:small; font-weight: bold">@Resources.Admin.AutoReady</label>
                            <div class="col-md-9" style="padding-top: 5px">
                                @Html.CheckBoxFor(model => model.AutoReady, new { @class = "icheckbox", @checked = "checked" })
                                @Html.ValidationMessageFor(model => model.AutoReady, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="Active" style="font-size:small; font-weight: bold">@Resources.Admin.Active</label>
                            <div class="col-md-9" style="padding-top: 5px">
                                @Html.CheckBoxFor(model => model.Active, new { @class = "icheckbox", @checked = "checked" })
                                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9 ">
                                <input type="submit" value=@Resources.Admin.Save class="btn btn-success btn-block" style="font-size:medium"/>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type='text/javascript' src='~/assets/js/plugins/icheck/icheck.min.js'></script>
    <script type="text/javascript" src="~/assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>

    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-select.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/jquery-validation/jquery.validate.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/maskedinput/jquery.maskedinput.min.js'></script>

    <script type="text/javascript">
        $('#myform').validate({});
    </script>
}

GestCTI/Views/CampaignPauseCodes/Index.cshtml
@model IEnumerable<GestCTI.Models.CampaignPauseCodes>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(@Resources.Admin.Campaigns, "Index", "Campaigns")</li>
    <li class="active">@Resources.Admin.PauseCodeCampaigns</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.PauseCodeCampaigns</h2>
</div>


<div class="panel panel-default tabs">
    <div class="panel-body tab-content">
        <div class="tab-pane active" id="tab-first">
            <h3 style="padding-bottom:15px">
                @Html.ActionLink(Resources.Admin.ActionCreateNew, "Create", null, new { @class = "fa fa-plus" })
            </h3>
            <table class="table Mydatatable" id="tabla-index">
                <thead>
                    <tr>
                        <th>
                            @Resources.Admin.PauseCode
                        </th>
                        <th>
                            @Resources.Admin.Campaign
                        </th>
                        <th>
                            @Resources.Admin.MaxDuration
                        </th>
                        <th>
                            @Resources.Admin.MaxDailyEvents
                        </th>
                        <th>
                            @Resources.Admin.AutoReady
                        </th>
                        <th>
                            @Resources.Admin.Active
                        </th>
                        <th>
                            @Resources.Admin.Options
                        </th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PauseCodes.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Campaign.Code)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaxDuration)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaxDailyEvents)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AutoReady)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Active)
                        </td>
                        <td>
                            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "btn btn-success btn-sm fa fa-edit info", title = Resources.Admin.ActionEdit })

                            @if (item.Active)
                            {
                                <a class="btn btn-danger btn-sm info fa fa-trash-o mb-control" data-box="#Modal_@item.Id" title="@Resources.Admin.Deactivate"></a>

                                @Html.Partial("Notifications", null, new ViewDataDictionary { { "IdItem", item.Id }, { "Icon", "fa fa-trash-o" }, { "Title", Resources.Admin.Deactivate + " " + Resources.Admin.PauseCodeCampaign }, { "Action", "Delete" }, { "Controller", "CampaignPauseCodes" }, { "Menssage", Resources.Admin.QuestionDeactivateM + " " + Resources.Admin.PauseCode + " " + Resources.Admin.With + " " + Resources.Admin.Name + ": " + item.PauseCodes.Name + " " + Resources.Admin.OfF + " " + Resources.Admin.Campaign + ": " + item.Campaign.Code + "?" } })
                            }
                            else
                            {
                                <a class="btn btn-warning btn-sm info glyphicon glyphicon-play mb-control" data-box="#Modal_@item.Id" title="@Resources.Admin.Activate"></a>

                                    @Html.Partial("Notifications", null, new ViewDataDictionary { { "IdItem", item.Id }, { "Icon", "glyphicon glyphicon-play" }, { "Title", Resources.Admin.Activate + " " + Resources.Admin.PauseCodeCampaign }, { "Action", "Activate" }, { "Controller", "CampaignPauseCodes" }, { "Menssage", Resources.Admin.QuestionActivateM + " " + Resources.Admin.PauseCode + " " + Resources.Admin.With + " " + Resources.Admin.Name + ": " + item.PauseCodes.Name + " " + Resources.Admin.OfF + " " + Resources.Admin.Campaign + ": " + item.Campaign.Code + "?" } })
                            }
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

@section scripts{

    <script type='text/javascript' src="~/assets/js/plugins/icheck/icheck.min.js"></script>
    <script src="~/assets/js/plugins/datatables/dataTablesLang.js"></script>
}