GestCTI/Controllers/CampaignTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestCTI.Models;
using GestCTI.Controllers.Auth;

namespace GestCTI.Controllers
{
    [CustomAuthorize(Roles = "admin")]
    public class CampaignTypesController : Controller
    {
        private DBCTIEntities db = new DBCTIEntities();

        // GET: CampaignTypes
        public ActionResult Index()
        {
            return View(db.CampaignType.ToList());
        }

        // GET: CampaignTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CampaignTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] CampaignType campaignType)
        {
            if (ModelState.IsValid)
            {
                db.CampaignType.Add(campaignType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(campaignType);
        }

        // GET: CampaignTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CampaignType campaignType = db.CampaignType.Find(id);
            if (campaignType == null)
            {
                return HttpNotFound();
            }
            return View(campaignType);
        }

        // POST: CampaignTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] CampaignType campaignType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campaignType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(campaignType);
        }

        // POST: CampaignTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CampaignType campaignType = db.CampaignType.Find(id);
            db.CampaignType.Remove(campaignType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestCTI/Views/CampaignTypes/Create.cshtml
@model GestCTI.Models.CampaignType

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(@Resources.Admin.Campaigns, "Index", "Campaigns")</li>
    <li>@Html.ActionLink(Resources.Admin.CampaignTypes, "Index")</li>
    <li class="active">@Resources.Admin.ActionCreateNew</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.ActionCreateNew </h2>
</div>

<div class="panel panel-default tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">@Resources.Admin.CampaignType</a></li>
    </ul>
    <div class="panel-body tab-content">
        <div class="col-md-6 col-lg-offset-3">
            <div class="tab-pane active" id="tab1">
                @using (Html.BeginForm("Create", "CampaignTypes", FormMethod.Post, new { id = "myform" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="control-label col-md-3" for="Name" style="font-size:small; font-weight: bold">@Resources.Admin.Name</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9 ">
                                <input type="submit" value=@Resources.Admin.Save class="btn btn-success btn-block" style = "font-size:medium"/>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type='text/javascript' src='~/assets/js/plugins/icheck/icheck.min.js'></script>
    <script type="text/javascript" src="~/assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>

    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-select.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/jquery-validation/jquery.validate.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/maskedinput/jquery.maskedinput.min.js'></script>

    <script type="text/javascript">
        $('#myform').validate({});
    </script>
}

GestCTI/Views/CampaignTypes/Edit.cshtml
@model GestCTI.Models.CampaignType

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(@Resources.Admin.Campaigns, "Index", "Campaigns")</li>
    <li>@Html.ActionLink(Resources.Admin.CampaignTypes, "Index")</li>
    <li class="active">@Resources.Admin.ActionEdit</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.ActionEdit </h2>
</div>

<div class="panel panel-default tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">@Resources.Admin.CampaignType</a></li>
    </ul>
    <div class="panel-body tab-content">
        <div class="col-md-6 col-lg-offset-3">
            <div class="tab-pane active" id="tab1">
                @using (Html.BeginForm("Edit", "CampaignTypes", FormMethod.Post, new { id = "myform" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            <label class="control-label col-md-3" for="Name" style="font-size:small; font-weight: bold">@Resources.Admin.Name</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9 ">
                                <input type="submit" value=@Resources.Admin.Save class="btn btn-success btn-block" style = "font-size:medium"/>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type='text/javascript' src='~/assets/js/plugins/icheck/icheck.min.js'></script>
    <script type="text/javascript" src="~/assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>

    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-select.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/jquery-validation/jquery.validate.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/maskedinput/jquery.maskedinput.min.js'></script>

    <script type="text/javascript">
        $('#myform').validate({});
    </script>
}

GestCTI/Views/CampaignTypes/Index.cshtml
@model IEnumerable<GestCTI.Models.CampaignType>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(@Resources.Admin.Campaigns, "Index", "Campaigns")</li>
    <li class="active">@Resources.Admin.CampaignTypes</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span>@Resources.Admin.CampaignTypes</h2>
</div>

<div class="panel panel-default tabs">

    <div class="panel-body tab-content">
        <div class="tab-pane active" id="tab-first">
            @*<h3 style="padding-bottom:15px">
                @Html.ActionLink(Resources.Admin.ActionCreateNew, "Create", null, new { @class = "fa fa-plus" })
            </h3>*@
            <table class="table Mydatatable" id="tabla-index">
                <thead>
                    <tr>
                        <th>
                            @Resources.Admin.Name
                        </th>
                        @*<th>
                            @Resources.Admin.Options
                        </th>*@
                    </tr>
                </thead>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            @*<td>
                                @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "btn btn-success btn-sm fa fa-edit info", title = Resources.Admin.ActionEdit })

                                <a class="btn btn-danger btn-sm info fa fa-trash-o mb-control" data-box="#Modal_@item.Id" title="@Resources.Admin.ActionDelete"></a>

                                @Html.Partial("Notifications", null, new ViewDataDictionary { { "IdItem", item.Id }, { "Icon", "fa fa-trash-o" }, { "Title", Resources.Admin.DeleteRecord }, { "Action", "Delete" }, { "Controller", "CampaignTypes" }, { "Menssage", Resources.Admin.QuestionDeleteM + " " + Resources.Admin.CampaignType + " " + Resources.Admin.With + " " + Resources.Admin.Name + ": " + item.Name + "?" } })
                            </td>*@
                        </tr>
                    }

            </table>
        </div>
    </div>
</div>

@section scripts{

    <script type='text/javascript' src="~/assets/js/plugins/icheck/icheck.min.js"></script>
    <script src="~/assets/js/plugins/datatables/dataTablesLang.js"></script>
}