GestCTI/Models/Company.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Campaign = new HashSet<Campaign>();
            this.Users1 = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SwitchCompanyId { get; set; }
        public int SwitchId { get; set; }
        public Nullable<int> CreateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> Campaign { get; set; }
        public virtual Switch Switch { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users1 { get; set; }
    }
}

GestCTI/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestCTI.Models;
using GestCTI.Controllers.Auth;

namespace GestCTI.Controllers
{
    [CustomAuthorize(Roles = "admin")]
    public class CompaniesController : Controller
    {
        private DBCTIEntities db = new DBCTIEntities();

        // GET: Companies
        public ActionResult Index()
        {
            var company = db.Company.Include(c => c.Switch).Include(c => c.Users);
            return View(company.ToList());
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            ViewBag.SwitchId = new SelectList(db.Switch, "Id", "Name");
            ViewBag.CreateBy = new SelectList(db.Users, "Id", "Username");
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,SwitchCompanyId,SwitchId,CreateBy")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Company.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SwitchId = new SelectList(db.Switch, "Id", "Name", company.SwitchId);
            ViewBag.CreateBy = new SelectList(db.Users, "Id", "Username", company.CreateBy);
            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Company.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            ViewBag.SwitchId = new SelectList(db.Switch, "Id", "Name", company.SwitchId);
            ViewBag.CreateBy = new SelectList(db.Users, "Id", "Username", company.CreateBy);
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,SwitchCompanyId,SwitchId,CreateBy")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SwitchId = new SelectList(db.Switch, "Id", "Name", company.SwitchId);
            ViewBag.CreateBy = new SelectList(db.Users, "Id", "Username", company.CreateBy);
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Company company = db.Company.Find(id);
            db.Company.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestCTI/Views/Companies/Create.cshtml
@model GestCTI.Models.Company

@{
    ViewBag.Title = "Create";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(Resources.Admin.Companies, "Index")</li>
    <li class="active">@Resources.Admin.ActionCreateNew</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.ActionCreateNew </h2>
</div>


<div class="panel panel-default tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">@Resources.Admin.Company</a></li>
    </ul>
    <div class="panel-body tab-content">
        <div class="col-md-6 col-lg-offset-3">
            <div class="tab-pane active" id="tab1">
                @using (Html.BeginForm("Create", "Companies", FormMethod.Post, new { id = "myform" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="control-label col-md-3" for="Name" style="font-size:small; font-weight: bold">@Resources.Admin.Name</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="SwitchCompanyId" style="font-size:small; font-weight: bold">@Resources.Admin.SwitchCompany</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.SwitchCompanyId, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                @Html.ValidationMessageFor(model => model.SwitchCompanyId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="SwitchId" style="font-size:small; font-weight: bold">Switch</label>
                            <div class="col-md-9">
                                @Html.DropDownList("SwitchId", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.SwitchId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="CreateBy" style="font-size:small; font-weight: bold">@Resources.Admin.CretedBy</label>
                            <div class="col-md-9">
                                @Html.DropDownList("CreateBy", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.CreateBy, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9 ">
                                <input type="submit" value=@Resources.Admin.Save class="btn btn-success btn-block" style="font-size:medium"/>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type='text/javascript' src='~/assets/js/plugins/icheck/icheck.min.js'></script>
    <script type="text/javascript" src="~/assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>

    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-select.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/jquery-validation/jquery.validate.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/maskedinput/jquery.maskedinput.min.js'></script>

    <script type="text/javascript">
        $('#myform').validate({});
    </script>
}

GestCTI/Views/Companies/Edit.cshtml
@model GestCTI.Models.Company

@{
    ViewBag.Title = "Edit";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(Resources.Admin.Companies, "Index")</li>
    <li class="active">@Resources.Admin.ActionEdit</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.ActionEdit </h2>
</div>


<div class="panel panel-default tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">@Resources.Admin.Company</a></li>
    </ul>
    <div class="panel-body tab-content">
        <div class="col-md-6 col-lg-offset-3">
            <div class="tab-pane active" id="tab1">
                @using (Html.BeginForm("Edit", "Companies", FormMethod.Post, new { id = "myform" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            <label class="control-label col-md-3" for="Name" style="font-size:small; font-weight: bold">@Resources.Admin.Name</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="SwitchCompanyId" style="font-size:small; font-weight: bold">@Resources.Admin.SwitchCompany</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.SwitchCompanyId, new { htmlAttributes = new { @class = "form-control", style = "font-size:small", required = "required" } })
                                @Html.ValidationMessageFor(model => model.SwitchCompanyId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="SwitchId" style="font-size:small; font-weight: bold">Switch</label>
                            <div class="col-md-9">
                                @Html.DropDownList("SwitchId", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.SwitchId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="CreateBy" style="font-size:small; font-weight: bold">@Resources.Admin.CretedBy</label>
                            <div class="col-md-9">
                                @Html.DropDownList("CreateBy", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.CreateBy, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9 ">
                                <input type="submit" value=@Resources.Admin.Save class="btn btn-success btn-block" style = "font-size:medium"/>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type='text/javascript' src='~/assets/js/plugins/icheck/icheck.min.js'></script>
    <script type="text/javascript" src="~/assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>

    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-select.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/jquery-validation/jquery.validate.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/maskedinput/jquery.maskedinput.min.js'></script>

    <script type="text/javascript">
        $('#myform').validate({});
    </script>
}

GestCTI/Views/Companies/Index.cshtml
@model IEnumerable<GestCTI.Models.Company>

@{
    ViewBag.Title = "Index";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li class="active">@Resources.Admin.Companies</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.Companies</h2>
</div>


<div class="panel panel-default tabs">

    <div class="panel-body tab-content">
        <div class="tab-pane active" id="tab-first">
            <h3 style="padding-bottom:15px">
                @Html.ActionLink(Resources.Admin.ActionCreateNew, "Create", null, new { @class = "fa fa-plus" })
            </h3>
            <table class="table Mydatatable" id="tabla-index">
                <thead>
                    <tr>
                        <th>
                            @Resources.Admin.Name
                        </th>
                        <th>
                           @Resources.Admin.SwitchCompany
                        </th>
                        <th>
                            Switch
                        </th>
                        <th>
                            @Resources.Admin.CretedBy
                        </th>
                        <th>
                            @Resources.Admin.Options
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SwitchCompanyId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Switch.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Users.Username)
                            </td>
                            <td>
                                @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "btn btn-success btn-sm fa fa-edit info", title = Resources.Admin.ActionEdit })

                                <a class="btn btn-danger btn-sm info fa fa-trash-o mb-control" data-box="#Modal_@item.Id" title="@Resources.Admin.ActionDelete"></a>

                                @Html.Partial("Notifications", null, new ViewDataDictionary { { "IdItem", item.Id }, { "Icon", "fa fa-trash-o" }, { "Title", Resources.Admin.DeleteRecord }, { "Action", "Delete" }, { "Controller", "Companies" }, { "Menssage", Resources.Admin.QuestionDeleteF + " " + Resources.Admin.Company + " " + Resources.Admin.With + " " + Resources.Admin.Name + ": " + item.Name + "?" } })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts{

    <script type='text/javascript' src="~/assets/js/plugins/icheck/icheck.min.js"></script>
    <script src="~/assets/js/plugins/datatables/dataTablesLang.js"></script>
}