GestCTI/Models/DispositionCampaigns.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispositionCampaigns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DispositionCampaigns()
        {
            this.Calls = new HashSet<Calls>();
        }
    
        public int Id { get; set; }
        public int IdDisposition { get; set; }
        public int IdCampaign { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calls> Calls { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual Dispositions Dispositions { get; set; }
    }
}

GestCTI/Controllers/DispositionCampaignsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestCTI.Models;
using GestCTI.Controllers.Auth;

namespace GestCTI.Controllers
{
    [CustomAuthorize(Roles = "admin")]
    public class DispositionCampaignsController : Controller
    {
        private DBCTIEntities db = new DBCTIEntities();

        // GET: DispositionCampaigns
        public ActionResult Index()
        {
            var dispositionCampaigns = db.DispositionCampaigns.Include(d => d.Campaign).Include(d => d.Dispositions);
            return View(dispositionCampaigns.ToList());
        }

        // GET: DispositionCampaigns/Create
        public ActionResult Create()
        {
            ViewBag.IdCampaign = new SelectList(db.Campaign, "Id", "Code");
            ViewBag.IdDisposition = new SelectList(db.Dispositions, "Id", "Name");
            return View();
        }

        // POST: DispositionCampaigns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,IdDisposition,IdCampaign,Description,Active")] DispositionCampaigns dispositionCampaigns)
        {
            if (ModelState.IsValid)
            {
                if (db.DispositionCampaigns.FirstOrDefault(p => p.IdCampaign == dispositionCampaigns.IdCampaign && p.IdDisposition == dispositionCampaigns.IdDisposition) == null)
                {
                    db.DispositionCampaigns.Add(dispositionCampaigns);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["errorNoty"] = Resources.Admin.TheDisposition + " " + dispositionCampaigns.Dispositions.Name + " " + Resources.Admin.ExistIntheCampaign + " " + dispositionCampaigns.Campaign.Name;
            }

            ViewBag.IdCampaign = new SelectList(db.Campaign, "Id", "Code", dispositionCampaigns.IdCampaign);
            ViewBag.IdDisposition = new SelectList(db.Dispositions, "Id", "Name", dispositionCampaigns.IdDisposition);
            return View(dispositionCampaigns);
        }

        // GET: DispositionCampaigns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DispositionCampaigns dispositionCampaigns = db.DispositionCampaigns.Find(id);
            if (dispositionCampaigns == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCampaign = new SelectList(db.Campaign, "Id", "Code", dispositionCampaigns.IdCampaign);
            ViewBag.IdDisposition = new SelectList(db.Dispositions, "Id", "Name", dispositionCampaigns.IdDisposition);
            return View(dispositionCampaigns);
        }

        // POST: DispositionCampaigns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IdDisposition,IdCampaign,Description,Active")] DispositionCampaigns dispositionCampaigns)
        {
            if (ModelState.IsValid)
            {
                if (db.DispositionCampaigns.FirstOrDefault(p => p.IdCampaign == dispositionCampaigns.IdCampaign && p.IdDisposition == dispositionCampaigns.IdDisposition) == null)
                {
                    DispositionCampaigns TempdispositionCampaigns = db.DispositionCampaigns.Find(dispositionCampaigns.Id);
                    TempdispositionCampaigns.Description = dispositionCampaigns.Description;
                    TempdispositionCampaigns.Active = dispositionCampaigns.Active;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["errorNoty"] = Resources.Admin.TheDisposition + " " + dispositionCampaigns.Dispositions.Name + " " + Resources.Admin.ExistIntheCampaign + " " + dispositionCampaigns.Campaign.Name;
            }
            ViewBag.IdCampaign = new SelectList(db.Campaign, "Id", "Code", dispositionCampaigns.IdCampaign);
            ViewBag.IdDisposition = new SelectList(db.Dispositions, "Id", "Name", dispositionCampaigns.IdDisposition);
            return View(dispositionCampaigns);
        }

        // POST: DispositionCampaigns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DispositionCampaigns dispositionCampaigns = db.DispositionCampaigns.Find(id);
            dispositionCampaigns.Active = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: DispositionCampaigns/Activate/5
        [HttpPost, ActionName("Activate")]
        [ValidateAntiForgeryToken]
        public ActionResult Activate(int id)
        {
            DispositionCampaigns dispositionCampaigns = db.DispositionCampaigns.Find(id);
            dispositionCampaigns.Active = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestCTI/Views/DispositionCampaigns/Create.cshtml
@model GestCTI.Models.DispositionCampaigns

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(@Resources.Admin.Campaigns, "Index", "Campaigns")</li>
    <li>@Html.ActionLink(Resources.Admin.DispositionCampaigns, "Index")</li>
    <li class="active">@Resources.Admin.ActionCreateNew</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.ActionCreateNew </h2>
</div>

<div class="panel panel-default tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">@Resources.Admin.DispositionCampaign</a></li>
    </ul>
    <div class="panel-body tab-content">
        <div class="col-md-6 col-lg-offset-3">
            <div class="tab-pane active" id="tab1">
                @using (Html.BeginForm("Create", "DispositionCampaigns", FormMethod.Post, new { id = "myform" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="control-label col-md-3" for="IdDisposition" style="font-size:small; font-weight: bold">@Resources.Admin.Disposition</label>
                            <div class="col-md-9">
                                @Html.DropDownList("IdDisposition", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.IdDisposition, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="IdCampaign" style="font-size:small; font-weight: bold">@Resources.Admin.Campaign</label>
                            <div class="col-md-9">
                                @Html.DropDownList("IdCampaign", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required" })
                                @Html.ValidationMessageFor(model => model.IdCampaign, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="Description" style="font-size:small; font-weight: bold">@Resources.Admin.Description</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", style = "font-size:small" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="Active">@Resources.Admin.Active</label>
                            <div class="col-md-9" style="padding-top: 5px">
                                @Html.CheckBoxFor(model => model.Active, new { @class = "icheckbox", @checked = "checked" })
                                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9 ">
                                <input type="submit" value=@Resources.Admin.Save class="btn btn-success btn-block"  style="font-size:medium"/>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type='text/javascript' src='~/assets/js/plugins/icheck/icheck.min.js'></script>
    <script type="text/javascript" src="~/assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>

    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-select.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/jquery-validation/jquery.validate.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/maskedinput/jquery.maskedinput.min.js'></script>

    <script type="text/javascript">
        $('#myform').validate({});
    </script>
}

GestCTI/Views/DispositionCampaigns/Edit.cshtml
@model GestCTI.Models.DispositionCampaigns

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(@Resources.Admin.Campaigns, "Index", "Campaigns")</li>
    <li>@Html.ActionLink(Resources.Admin.DispositionCampaigns, "Index")</li>
    <li class="active">@Resources.Admin.ActionEdit</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.ActionEdit</h2>
</div>

<div class="panel panel-default tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">@Resources.Admin.DispositionCampaign</a></li>
    </ul>
    <div class="panel-body tab-content">
        <div class="col-md-6 col-lg-offset-3">
            <div class="tab-pane active" id="tab1">
                @using (Html.BeginForm("Edit", "DispositionCampaigns", FormMethod.Post, new { id = "myform" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="control-label col-md-3" for="IdDisposition" style="font-size:small; font-weight: bold">@Resources.Admin.Disposition</label>
                            <div class="col-md-9">
                                @*@Html.DropDownList("IdDisposition", null, htmlAttributes: new { @class = "form-control select", required = "required", disabled="disabled" })*@
                                <label class="control-label" style="font-size:small">@Model.IdDisposition</label>
                                @Html.ValidationMessageFor(model => model.IdDisposition, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="IdCampaign" style="font-size:small; font-weight: bold">@Resources.Admin.Campaign</label>
                            <div class="col-md-9">
                                @*@Html.DropDownList("IdCampaign", null, htmlAttributes: new { @class = "form-control select", style = "font-size:small", required = "required", disabled = "disabled" })*@
                                <label class="control-label" style="font-size:small">@Model.IdCampaign</label>
                                @Html.ValidationMessageFor(model => model.IdCampaign, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="Description" style="font-size:small; font-weight: bold">@Resources.Admin.Description</label>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", style = "font-size:small" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="Active" style="font-size:small; font-weight: bold">@Resources.Admin.Active</label>
                            <div class="col-md-9" style="padding-top: 5px">
                                @Html.CheckBoxFor(model => model.Active, new { @class = "icheckbox", @checked = "checked" })
                                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9 ">
                                <input type="submit" value=@Resources.Admin.Save class="btn btn-success btn-block" style="font-size:medium" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type='text/javascript' src='~/assets/js/plugins/icheck/icheck.min.js'></script>
    <script type="text/javascript" src="~/assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>

    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/bootstrap/bootstrap-select.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/jquery-validation/jquery.validate.js'></script>
    <script type='text/javascript' src='~/assets/js/plugins/maskedinput/jquery.maskedinput.min.js'></script>

    <script type="text/javascript">
        $('#myform').validate({});
    </script>
}

GestCTI/Views/DispositionCampaigns/Index.cshtml
@model IEnumerable<GestCTI.Models.DispositionCampaigns>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <li>@Html.ActionLink(@Resources.Login.Home, "Index", "Admin")</li>
    <li>@Html.ActionLink(@Resources.Admin.Campaigns, "Index", "Campaigns")</li>
    <li class="active">@Resources.Admin.DispositionCampaigns</li>
}

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> @Resources.Admin.DispositionCampaigns</h2>
</div>

<div class="panel panel-default tabs">
    <div class="panel-body tab-content">
        <div class="tab-pane active" id="tab-first">
            <h3 style="padding-bottom:15px">
                @Html.ActionLink(Resources.Admin.ActionCreateNew, "Create", null, new { @class = "fa fa-plus" })
            </h3>
            <table class="table Mydatatable" id="tabla-index">
                <thead>
                    <tr>
                        <th>
                            @Resources.Admin.Disposition
                        </th>
                        <th>
                            @Resources.Admin.Campaign
                        </th>
                        <th>
                            @Resources.Admin.Description
                        </th>
                        <th>
                            @Resources.Admin.Active
                        </th>
                        <th>
                            @Resources.Admin.Options
                        </th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Dispositions.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Campaign.Code)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Active)
                        </td>
                        <td>
                            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "btn btn-success btn-sm fa fa-edit info", title = Resources.Admin.ActionEdit })

                            @if (item.Active)
                            {
                                <a class="btn btn-danger btn-sm info fa fa-trash-o mb-control" data-box="#Modal_@item.Id" title="@Resources.Admin.Deactivate"></a>

                                @Html.Partial("Notifications", null, new ViewDataDictionary { { "IdItem", item.Id }, { "Icon", "fa fa-trash-o" }, { "Title", Resources.Admin.Deactivate + " " + Resources.Admin.DispositionCampaign }, { "Action", "Delete" }, { "Controller", "DispositionCampaigns" }, { "Menssage", Resources.Admin.QuestionDeactivateM + " " + Resources.Admin.Disposition + " " + Resources.Admin.With + " " + Resources.Admin.Name + ": " + item.Dispositions.Name + " " + Resources.Admin.OfF + " " + Resources.Admin.Campaign + ": " + item.Campaign.Code + "?" } })
                            }
                            else
                            {
                                <a class="btn btn-warning btn-sm info glyphicon glyphicon-play mb-control" data-box="#Modal_@item.Id" title="@Resources.Admin.Activate"></a>

                                    @Html.Partial("Notifications", null, new ViewDataDictionary { { "IdItem", item.Id }, { "Icon", "glyphicon glyphicon-play" }, { "Title", Resources.Admin.Activate + " " + Resources.Admin.DispositionCampaign }, { "Action", "Activate" }, { "Controller", "DispositionCampaigns" }, { "Menssage", Resources.Admin.QuestionActivateM + " " + Resources.Admin.Disposition + " " + Resources.Admin.With + " " + Resources.Admin.Name + ": " + item.Dispositions.Name + " " + Resources.Admin.OfF + " " + Resources.Admin.Campaign + ": " + item.Campaign.Code + "?" } })
                            }
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

@section scripts{

    <script type='text/javascript' src="~/assets/js/plugins/icheck/icheck.min.js"></script>
    <script src="~/assets/js/plugins/datatables/dataTablesLang.js"></script>
}